# Generated by Django 3.1.2 on 2022-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_post_likeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hitCount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='조회수'),
        ),
    ]
