# Generated by Django 3.1.2 on 2022-03-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_user_followuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FollowUser',
            new_name='followUser',
        ),
    ]
